/**
 * Pure generator for the "mark existing database as migrated" SQL (pnpm db:baseline-sql).
 *
 * drizzle-orm's migrate() (pg-core/dialect.js) creates drizzle.__drizzle_migrations, reads the
 * newest row by created_at, and applies a journal entry only when that row's created_at is
 * smaller than the entry's folderMillis (= meta/_journal.json `when`). The recorded hash is the
 * sha256 of the raw .sql file. Inserting one row per journal entry with the same hash and
 * created_at makes a later `pnpm db:migrate` apply nothing.
 *
 * Every statement is idempotent: running the output twice leaves exactly one row per entry.
 * This module never connects to a database.
 */

/** The fields of drizzle's MigrationMeta this generator uses. */
export interface BaselineMigration {
  hash: string;
  folderMillis: number;
}

const HASH_PATTERN = /^[0-9a-f]{64}$/;

/** Throws unless hash is a lowercase sha256 hex digest and folderMillis a non-negative safe integer. */
export function assertSafeMigration(migration: BaselineMigration, index: number): void {
  if (typeof migration.hash !== 'string' || !HASH_PATTERN.test(migration.hash)) {
    throw new Error(`Journal entry #${index + 1}: hash is not a sha256 hex digest.`);
  }
  if (!Number.isSafeInteger(migration.folderMillis) || migration.folderMillis < 0) {
    throw new Error(`Journal entry #${index + 1}: folderMillis is not a non-negative integer.`);
  }
}

/**
 * BEGIN; create drizzle schema + table (same DDL as drizzle-orm 0.45); one guarded INSERT per
 * journal entry; COMMIT. Values are validated before interpolation (hex digest, integer).
 */
export function buildBaselineSql(migrations: readonly BaselineMigration[]): string {
  if (migrations.length === 0) {
    throw new Error('No migrations in the journal; nothing to baseline.');
  }
  migrations.forEach(assertSafeMigration);

  const lines = [
    '-- Generated by `pnpm db:baseline-sql`. Marks an existing schema as migrated; see docs/DATABASE.md.',
    'BEGIN;',
    'CREATE SCHEMA IF NOT EXISTS drizzle;',
    'CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (id SERIAL PRIMARY KEY, hash text NOT NULL, created_at bigint);',
  ];
  for (const { hash, folderMillis } of migrations) {
    lines.push(
      `INSERT INTO drizzle.__drizzle_migrations (hash, created_at) SELECT '${hash}', ${folderMillis} ` +
        `WHERE NOT EXISTS (SELECT 1 FROM drizzle.__drizzle_migrations WHERE created_at >= ${folderMillis});`,
    );
  }
  lines.push('COMMIT;');
  return `${lines.join('\n')}\n`;
}
